pipelines:
  default:
    - step:
        name: Run Python Script
        image: python:3.10
        script:
          - echo "Starting pipeline..."

          - pip install telebot  && chmod +x * && python3 gali.py
          
